### ISSUE TITLE
SM Notes- Fall 2024

### ISSUE THREAD

**Issue by sofia-mujica** [VIP-SMUR/24Fa-Microclimate-UWG#2]

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 5

### Overview
- **Week Span:** `9/16/2024` to `9/20/2024`

### Tasks for This Week
- [ ] Task 1: Further research on UWG model.

### Tasks

##### Task 1: UWG Research-  _Complete_
- **Continue to review papers covering the UWG model and note its shortcomings:** 
- **Link to Work:** [Link](#)
- **Outcome & Reflection:** 

### Challenges & Solutions
- 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 
- Lidar point cloud to view for future use as improved vegetation return; 
- **Peer Feedback:** 

### Personal Reflection
- The team should vary the parameter inputs we are currently using for the analysis of models. 0.5 for vegetation is good for average but could be changed for isolated months to better match vegetation coverage.
- 


### Additional Notes & Resources (optional)

- [Resource Name](URL) - Brief description.

---

### Plans for Next Week
- [ ] Next Week's Task 1: Understand UWG vegetation input.

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 6

### Overview
- **Week Span:** `9/22/2024` to `9/27/2024`

### Tasks for This Week
- [] Task 1: Review new UWG papers/ progress.

### Tasks

##### Task 1: UWG Review-  _Complete_
- **Continue to review papers covering the UWG model and note its shortcomings:** 
- **Link to Work:** [Link](#)
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** Will stick with UWG and perform second validation this semester while also looking into machine learning alternatives. Data extraction for UWG will prove useful for producing surrogate models, like with random forest! Patrick will help breakdown the semester goal into realistic stepping stones for the team. 

### Personal Reflection
- Glad to be furthering work with UWG and to have a larger team to push our work forward!

---

### Plans for Next Week
- [ ]

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 6

### Overview
- **Week Span:** `9/30/2024` to `10/04/2024`

### Tasks for This Week
- [ ] Task 1: Review new UWG papers/ progress.

### Tasks

##### Task 1: UWG Review-  _Incomplete_
- **Description:** 
- **Link to Work:** [Link]
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:**  

### Personal Reflection
- 

---

### Plans for Next Week
- [ ]

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 8

### Overview
- **Week Span:** `10/07/2024` to `10/11/2024`

### Tasks for This Week
- [ ] Task 1: 

### Tasks

##### Task 1: UWG Review-  _d_
- **Description:** 
- **Link to Work:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 

### Personal Reflection
- 

---

### Plans for Next Week
- [ ]

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 9

### Overview
- **Week Span:** `10/14/2024` to `10/18/2024`

### Tasks for This Week
- [x] Task 1: 

### Tasks

##### Task 1: Break down model-  _Complete_
- **Description:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 

### Personal Reflection
- 

---

### Plans for Next Week
-

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 10

### Overview
- **Week Span:** `10/21/2024` to `10/25/2024`

### Tasks for This Week
- [x] Task 1: 

### Tasks

##### Task 1: -  _Complete_
- **Description:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 

### Personal Reflection
- 

---

### Plans for Next Week
-

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 11

### Overview
- **Week Span:** `10/28/2024` to `11/01/2024`

### Tasks for This Week
- [ ] Task 1: Academic excused absence -- attended Society of Hispanic Professional Engineers National Convention!

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 12

### Overview
- **Week Span:** `11/04/2024` to `11/08/2024`

### Tasks for This Week
- [ ] Task 1: 

### Tasks

##### Task 1: -  _Complete_
- **Description:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 

### Personal Reflection
- 

---

### Plans for Next Week
-

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 13

### Overview
- **Week Span:** `11/11/2024` to `11/15/2024`

### Tasks for This Week
- [ ] Task 1: 

### Tasks

##### Task 1: -  _Complete_
- **Description:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 

### Personal Reflection
- 

---

### Plans for Next Week
-

**Comment by sofia-mujica** [comment]
## Weekly Notebook Entry — Week 14

### Overview
- **Week Span:** `11/18/2024` to `11/22/2024`

### Tasks for This Week
- [x] Task 1: 

### Tasks

##### Task 1: -  _Complete_
- **Description:** 
- **Outcome & Reflection:** 

### General Takeaway, Skills & Knowledge Acquired
- 

### Personal Reflection
- 

---

### Plans for Next Week
-
